version: "3.9"

services:
  app:
    image: service-name-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile

  web:
    image: service-name-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app

  db:
    image: service-name-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume:
